[project]
name = "pyclack-cli"
version = "0.4.1"
description = "A python library for building interactive command line interfaces effortlessly. Inspired by clack.cc"
readme = "README.md"
requires-python = ">=3.14"
authors = [
    { name = "Edoardo Balducci", email = "edoardoba2004@gmail.com" },
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "readchar",
    "rich>=15.0.0",
]

[project.urls]
Homepage = "https://github.com/Bbalduzz/pyclack"

[project.optional-dependencies]
core = ["readchar", "rich>=15.0.0"]
prompts = ["readchar", "rich>=15.0.0"]
all = ["readchar", "rich>=15.0.0"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pyclack"
module-root = "src"
